#
#  SoKnight's TradeToChat config file v1.2.0
#
General:
  # Формат сообщения в чате остальным игрокам
  TradeFormat: "&6[T] &b%player% &fопубликовал %item%&f."
  # Стандартный цвет имени предмета вместо %item%
  DefaultNameColor: 'AQUA'
  # Отправлять ли сообщение о трейде отправителю команды
  SendToYourself: true
  # Кулдаун использования команды (сек.)
  Cooldown: 60
Messages:
  NoPermissions: "&cНедостаточно прав."
  OnlyForPlayers: "&cКоманда доступна только для игрока."
  Cooldown: "&cПодождите ещё %time% сек. перед тем, как повторить команду."
  MainHandEmpty: "&cДержите предмет, который хотите опубликовать, в своей руке."
  PublicSuccess: "&fПредмет '%item%' &fуспешно опубликован."
  SuccessReloaded: "&fTradeToChat перезагружен."