name: TradeToChat
main: ru.soknight.ttc.TradeToChat
version: 1.1
api-version: 1.14
commands:
  ttc:
    aliases: [tradetochat]
    description: Reload this plugin
  public:
    aliases: [trade]
    description: Public trade to chat
permissions:
  ttc.public:
    default: true
  ttc.public.bypass:
    default: op
  ttc.ttc:
    default: op